### ISSUE TITLE
requireAuthenticatedClient=false results in "Initiate Auth method not supported." error

### ISSUE THREAD

**Issue by dguisinger** [adam-fowler/soto-cognito-authentication-kit#10]
I believe this code to be incorrect.   When setting requireAuthenticatedClient=false, the request is still being made to initAuthRequest with authFlow: .adminUserPasswordAuth, which results in the error: "InvalidParameterException: Initiate Auth method not supported."   I believe it should be setting it to .userPasswordAuth.

```
    public func authenticate(
        username: String,
        password: String,
        requireAuthenticatedClient: Bool = true,
        clientMetadata: [String: String]? = nil,
        context: CognitoContextData,
        on eventLoop: EventLoop
    ) -> EventLoopFuture<CognitoAuthenticateResponse> {
        var authParameters : [String: String] = [
            "USERNAME":username,
            "PASSWORD": password
        ]
        authParameters["SECRET_HASH"] = secretHash(username: username)

        return self.initiateAuthRequest(authFlow: .adminUserPasswordAuth,
                                        authParameters: authParameters,
                                        requireAuthenticatedClient: requireAuthenticatedClient,
                                        clientMetadata: clientMetadata,
                                        context: context,
                                        on: eventLoop)
    }
```

**Comment by adam-fowler** [comment]
Looks like you're right. I'll fix and release a patch

**Comment by adam-fowler** [comment]
v2.2.0 is out and includes this fix

**Comment by dguisinger** [comment]
@adam-fowler Looks like I can authenticate now, however I don't know if there is still issues with this auth flow or if I am doing something wrong.

If i set password reset required in Cognito, instead of getting a challenge in response to authentication, I am getting "passwordResetRequiredException".  My code in the authenticate().flatMap {} closure is not triggering, so I can't check for a challenge in the response.

**Comment by adam-fowler** [comment]
That is how it should work. According to AWS docs https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminResetUserPassword.html

"When a developer calls this API, the current password is invalidated, so it must be changed. If a user tries to sign in after the API is called, the app will get a PasswordResetRequiredException exception back and should direct the user down the flow to reset the password, which is the same as the forgot password flow."

Think you'll need to call `CognitoIdentityProvider.ConfirmForgotPassword` to set new password.

**Comment by adam-fowler** [comment]
Just added `forgotPassword`/`confirmForgotPassword` as it was really simple. You should be able to call `confirmForgotPassword` to set a new password. This is on the main branch

**Comment by dguisinger** [comment]
Oh!   They aren't the same thing, sorry ... I was thinking i should be getting a challenge response and was completely confused why I was getting the exception.
